# Generated by Django 3.2 on 2022-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='邮箱')),
                ('lastSentTime', models.DateTimeField(auto_now_add=True, verbose_name='最后一次发送时间')),
                ('code', models.CharField(max_length=8, verbose_name='验证码')),
            ],
        ),
    ]
