# Generated by Django 3.2 on 2022-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_got_th'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrant1024', models.CharField(max_length=20, verbose_name='warrant')),
                ('username', models.CharField(max_length=20, verbose_name='被谁领取')),
            ],
        ),
    ]
