# Generated by Django 3.2 on 2022-10-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_alter_cards_cardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cardID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='卡牌ID'),
        ),
    ]
